# Generated by Django 5.0.7 on 2024-08-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_2fa_enabled',
        ),
    ]
