# Generated by Django 5.0.7 on 2024-08-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0011_reserva_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
