# Generated by Django 5.0.7 on 2024-08-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0014_campo_latitude_campo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo_gramado',
            field=models.CharField(blank=True, choices=[('natural', 'Natural'), ('sintetico', 'Sintético')], default='natural', max_length=50, null=True),
        ),
    ]
