# Generated by Django 5.0.7 on 2024-08-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0016_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='campos.campo'),
        ),
    ]
