# Generated by Django 5.0.8 on 2024-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0017_alter_comentario_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
