# Generated by Django 5.0.8 on 2024-09-23 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0018_reserva_cancelada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelada', False)), fields=('campo', 'data_reserva', 'hora_inicio'), name='unique_reserva_ativa'),
        ),
    ]
