# Generated by Django 5.0.8 on 2024-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0020_reservacancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacancelada',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
